name="ixo-notifications-worker"
main="src/index.ts"
node_compat = true

compatibility_date = "2022-11-22"

[vars]
AUTHORIZATION=""
NETWORK=""

[[ d1_databases ]]
binding = "Notifications"
database_name = "notifications"
database_id = ""
