name="ixo-notifications-worker"
main="src/index.ts"
node_compat = true

compatibility_date = "2022-11-22"

[vars]
AUTHORIZATION=""
AIRTABLE_BASE_ID=""
AIRTABLE_API_KEY=""
AIRTABLE_TABLE_NOTIFICATIONS=""

[[ d1_databases ]]
binding = "Notifications"
database_name = "notifications"
database_id = ""
