name="ixo-notifications-worker"
main="src/index.ts"
compatibility_date = "2022-11-22"
node_compat = true

account_id=""
workers_dev = true

kv_namespaces = [ 
  { binding = "TESTERS", preview_id = "", id = "" }
]

[vars]
AUTHORIZATION=""
AIRTABLE_BASE_ID=""
AIRTABLE_API_KEY=""
AIRTABLE_TABLE_NOTIFICATIONS=""

[[ d1_databases ]]
binding = "Notifications"
database_name = "notifications"
database_id = ""
